### ISSUE TITLE
readline: Terminal breaks with a newline `\n` prompt

### ISSUE THREAD

**Issue by str1ngs-bytes** [lmorg/murex#470] opened 2022-10-12 10:33 UTC

**Comment by lmorg** [comment] 2022-10-13 08:35
Ahh ok, that makes sense. :)

The prompt it intended to be only a single line by design however the effect you're seeing is definitely readline not handling the new line correctly (it should either strip it or be rewritten to support multi-line prompts).

The reason I say it's not intended to be multi-line "by design" is because the additional helper detail is intended to be supplied via the "hint" text: https://github.com/lmorg/readline/blob/master/instance.go#L59

So you'd have code that might look a little like:
```
// WARNING: this code has been directly typed into Github and thus untested. So it might not compile verbatim.

rl.SetPrompt("$ ")
rl.HintText = func([]rune, int) []rune {
    return []rune("User Jhon")
}()
```

The idea behind this design is so that the additional line in most people's multi-line prompts can be context aware. Each time you press a key the HintText function (which is the `func` you've assigned to the `HintText` variable above) gets called with `[]rune` being the entire text that the user has inputted thus far, and the `int` being the cursor position.

This is means you can do some cool stuff like:
```
// WARNING: this code has been directly typed into Github and thus untested. So it might not compile verbatim.

rl.SetPrompt("$ ")
rl.HintText = func(text []rune, pos int) []rune {
    hint := fmt.Sprintf("You have typed: %s\nYour cursor position is %d", string(text), pos)

    return []rune(hint)
}()
```

That all said, I'm not totally against adding multi-line prompt support to readline. It just wasn't part of the original intended design.

<hr>

As an aside, you can also change the formatting of the hint text via `HintFormatting` (https://github.com/lmorg/readline/blob/master/instance.go#L64):
```
// WARNING: this code has been directly typed into Github and thus untested. So it might not compile verbatim.

rl.SetPrompt("$ ")
rl.HintText = func([]rune, int) []rune {
    return []rune("User Jhon")
}()

rl.HintFormatting = ""         // no formatting
rl.HintFormatting = "\x1b[41m" // red background
// etc
```

**Closed** 2022-10-20 17:11 UTC
Labels: bug, tooling
