### ISSUE TITLE
= spaces parsing error in `export`

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#679] opened 2023-08-12 15:19 UTC
**Describe the bug:**
`export JAVA_HOME = ${dirname ${dirname ${readlink -f ${which javac}}}}`
works fine

however, 
` export JAVA_HOME=${dirname ${dirname ${readlink -f ${which javac}}}}`
Error in `export` (0,3): error parsing export parameters. Expected: name[=value]

note the spaces around `=`

I would recommend relaxing the syntax to allow spaces, or better...  removing it completely in favor of the `->` syntax.

your pick

**Comment by lmorg** [comment] 2023-08-12 15:41
`export` already works fine without spaces:
```
~ » export foo=bar
~ » $foo
bar                                                                                                                                                                               ~ » export foo=${out baz}
~ » $foo
baz
```
also `export` already supports `->` syntax
```
~ » out world -> export hello
~ » $hello
world
```
There might still be a parsing bug here where the output of the subshell?

**Comment by orefalo** [comment] 2023-08-12 15:51
absolutely

```
.murex_modules » export JAVA_HOME = ${dirname ${dirname ${readlink -f ${which javac}}}}
Error in `export` (0,1): error parsing export parameters. Expected: name[=value]
.murex_modules » out ${dirname ${dirname ${readlink -f ${which javac}}}}
/Library/Java/JavaVirtualMachines/zulu-18.jdk/Contents/Home
```

full code is here https://github.com/orefalo/murex-module-javahome

**Comment by orefalo** [comment] 2023-08-12 15:52
I fixed it with `${dirname ${dirname ${readlink -f ${which javac}}}} -> export JAVA_HOME`

**Comment by lmorg** [comment] 2023-08-12 16:12
Ahhh, the issue is the opposite of what you described:
```
~ » export foo = bar
Error in `export` (0,1): error parsing export parameters. Expected: name[=value]
~ » export foo=bar
~ »
```
so it doesn't work with spaces. Yeah I should get that fixed but it would work with the newer (and also undocumented) dot notation:
```
~ » ENV.foo = "bar"
~ » $foo
bar
```

---

> I fixed it with `${dirname ${dirname ${readlink -f ${which javac}}}} -> export JAVA_HOME`

You don't need a subshell there:
```
dirname ${dirname ${readlink -f ${which javac}}} -> export JAVA_HOME
```
would work. As should the newer notation in `develop`:
```
$ENV.JAVA_HOME = dirname(dirname(readlink -f which(javac)))
```

---

As an aside, why are you calling `dirname` twice? I don't know if you're aware but there is an undocumented (_sigh_ I really need to write more documentation!) data type called `path` that allows you to treat paths like arrays. eg
```
~ » which java
/usr/bin/java
~ » which java -> :path: [0]
/
~ » which java -> :path: [1]
usr
~ » which java -> :path: [2]
bin
~ » which java -> :path: [3]
java
```
There might be bugs with that because it's a relatively recent feature which hasn't been used a whole lot in real world code. But some variables, like `$PWD` already default to `path`:
```
# return the last element in current working directory
~ » $PWD[-1]
lau
```

**Comment by orefalo** [comment] 2023-08-12 16:23
Plenty of good tips which I will incorporate in the code. string with `$ENV.JAVA_HOME = dirname(dirname(readlink -f which(javac)))`

yes, I got mixed up - 'it doesn't work with spaces' - that's what I meant.

I forgot why I am calling dirname multiple times  ;-)
 - I wrote the original fish script a while ago and yeah.. no comments
 - it's most likely for good reasons. will double check.

**Comment by orefalo** [comment] 2023-08-12 16:27
I remember...

The goal is to get the JAVA_HOME, a clean path without `../..`
since `javac` typically lands in `$JAVAHOME/bin/javac`, the double dirname allows me to get a clean path without '../..'

**Comment by lmorg** [comment] 2023-11-19 12:56
@orefalo 
This will be incorperated in v5.3 (already have pre-release code written and pushed to `prerelease-5.3` branch

**Closed** 2023-12-08 13:22 UTC
Labels: bug, in progress
