### ISSUE TITLE
[Should murex] Adhere to the XDG base directory specification

### ISSUE THREAD

**Issue by piegamesde** [lmorg/murex#317] opened 2021-04-25 21:03 UTC
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

I just found `.murex-modules` in my $HOME. Please don't do that.

**Comment by lmorg** [comment] 2021-04-26 12:41
Yes, I had debated this several times myself. But one issue I've never been able to resolve is what happens when you're running _murex_ on a non-UNIX platform and how do you communicate this message clearly with users across all operating systems? The issue is _murex_ actually supports more platforms than XDG does and having a `.config/murex` directory is a little counter-intuitive for those not running Linux, let alone those not even running a POSIX OS.

I'm open to discussion on this because I do write a lot of profile data to disk (as documented here: https://murex.rocks/docs/user-guide/profile.html) but the solution needs to be easily described and predictable -- which XDG isn't. Which is why I followed the precedent set by most previous shells. Albeit I do acknowledge that there are outliers that do follow XDG.

I'd be interesting in the thoughts of some other users here because from the issues I've seen raised over the years, it seems there are a users from a broad range of platforms. So I'd love to see a discussion with other peoples thoughts before I commit any changes.

As for the change itself, it should be very simple. As stated above, I've debated this several times myself so I'd already written the code in a way that the paths can be changed later if I chose to.

**Comment by piegamesde** [comment] 2021-04-26 20:15
This issue comes up a lot. A common solution is to use the XDG specification for Linux and the respective native equivalent on other platforms. This is for example what the [`directories`](https://docs.rs/directories-next/2.0.0/directories_next/) crates do in the Rust ecosystem.

**Comment by lmorg** [comment] 2021-04-26 21:56
But if every platform has a different path for `.murex_profile` what you end up with isn't something that is easily described nor predictable. Which is the exact opposite of the goals behind _murex_.

What's worse here is normally I'd offer override flags or `config` settings to alter _murex_'s default behaviour for those who do have bespoke preferences, but that wouldn't work here either. Having a flag to change where `.murex_modules` is would be pretty annoying as an end user as it's not a persistent setting; and `config` values would need to be read from _murex_ profiles -- ie the very files we're trying to define new storage locations of. The obvious workaround here is an environmental variable but the XDG spec is too overblown and not Windows friendly (due to the delimiter character differing from what Windows typically uses to delimit paths in env vars) and creating a new environmental variable specifically for this purpose seems as user hostile as a command line flag.

Maybe the simplest path forward here is to set the profile path as a compile time option?

A compile time option means I can still standardise on a path across all platforms for lesser experienced users benefit and write documentation to that effect, but at the same time offer more control for more experienced users.

I wont pretend to have spent any more than 5 minutes thinking about using a compile time flag to solve this problem though. So there may be really strong reasons not to go down this route. As per my previous comment, I welcome a discussion on this.

**Comment by piegamesde** [comment] 2021-04-26 22:08
> But if every platform has a different path for `.murex_profile` what you end up with isn't something that is easily described nor predictable.

Think of the user's perspective. Users switch less between operating systems, and more between applications (by an order of magnitude). It is more confusing to have every application put its data somewhere else. If you put the data at the system's common location, they can simply look for it where all other applications store their data too.

**Comment by lmorg** [comment] 2021-04-26 22:44
> Users switch less between operating systems, and more between applications 

I routinely switch between different operating systems :) The very reason `.murex_modules/` exists in the first place was so that I *could* standardise my _murex_ install across different platforms. I wrote about it here: https://murex.rocks/docs/user-guide/modules.html

> If you put the data at the system's common location, they can simply look for it where all other applications store their data too.

That common location is technically `~` -- even on Linux. XDG is preferred by many on Linux but it's still just one of many competing standards. Furthermore, there is already a precedent for shells to have their profiles in `~`. So I'd argue the current settings already follows the "system's common location" rule (which is precisely why I defaulted there).

Now I do get why `~` is unpopular for some. If truth be told it used to bug me in the 90s when I was first introduced to desktop Linux too. But thus far I've not heard a compelling argument for why platform specific paths wouldn't break one of the core tenets _murex_ with regards to usability, portability and predictability. If someone came from Linux and typed `vi ~/.murex_profile` they'd expect their _murex_ profiles just as they would get on Bash, Csh or Zsh. Furthermore how confused would users on Windows or Darwin be if they read Linux instructions only to find it doesn't work (and visa versa). If you have to include multiple operating system specific headings to the instructions then the default behaviour is poor.

In theory I could have a new shortcut variable (like `~`) for the config path. But that could risk unexpected behaviour (ie a variable expanding where users are not expecting one to). Plus `~/.$SHELL_profile` is already muscle memory for some. Another option is to keep the current defaults but have it alterable as a compile time option. So the documentation is standardised for all but those who purposely changed it. But then I'd still need to introduce additional tooling to expose what that custom path is -- and if I have to do that then is it really any different to having different paths for different operating systems.

Ultimately I need a greater sample size to really judge how best to proceed on this because the only data I currently have is yourself and myself. And as much as I'll bend over backwards to support additional optional behaviours for anyone who'll request it; changing the core defaults for everyone based on one person's preferences isn't any smarter than sticking with `~` because of it being my own preference. In short, before I'm prepared to make any change to core default behaviour here, I need to hear the views of other _murex_ users.

**Comment by piegamesde** [comment] 2021-04-26 23:35
> That common location is technically ~ -- even on Linux. XDG is preferred by many on Linux but it's still just one of many competing standards.

I don't know of any significant other standards, except "dump it in $HOME". 

> Furthermore, there is already a precedent for shells to have their profiles in ~.

I thought Murex was about not reproducing the mistakes of its precedents and do things right™? But even then, there should be no other files directly in home other than `.murex_profile`.

------

Is putting a symlink an option? The data is stored at the "correct" location yet can still be found. And one can simply delete the symlink if one wants to; nothing else will break.

Instead of adding a compile option, you could make the path configurable by a custom environment variable. It wouldn't be great, but it would allow for custom configuration without having to recompile the application.

In any case, it'd be great if the application data was split into data/config/cache, independently where it's put in the end. That'll at least keep the door open for the future, and IMO it's a good idea to do anyways.

**Comment by lmorg** [comment] 2021-04-27 10:56
> Is putting a symlink an option? The data is stored at the "correct" location yet can still be found. And one can simply delete the symlink if one wants to; nothing else will break.

That's not a bad suggestion

> Instead of adding a compile option, you could make the path configurable by a custom environment variable. It wouldn't be great, but it would allow for custom configuration without having to recompile the application.

The issue I have with a custom env var is that it's not persistent. There's a lot of edge cases were an environmental variable might not get set and that would result in _murex_'s behaviour changing.

It's a similar reason I'm still a bit nervous about using XDG. Those variables are at least expected to be persistent within an X (and presumably Wayland) session but what about serial connections or dropping to a `/dev/tty` (as opposed to a PTS/PTY)? The XDG model breaks down a little with consoles.

In fact, where are `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME` set? It doesn't appear to be set on my ArchLinux systems nor any of my CentOS and Ubuntu Server systems either. If I do go down the $XDG route with symlinks then I'd need to understand a little more about when those env vars are set and not set.

Also, if you don't mind me asking, do you use _murex_ more as a shell or as a scripting language? Or a little of both?

> In any case, it'd be great if the application data was split into data/config/cache, independently where it's put in the end. That'll at least keep the door open for the future, and IMO it's a good idea to do anyways.

Cache gets written to the temp directory (typically `/tmp` but there are established env vars for those: https://golang.org/pkg/os/#TempDir)

Data and config are one and the same in _murex_ since all data is code and all config is code. A bit like LISP. So there isn't really a meaningful distinction to make here.

> I thought Murex was about not reproducing the mistakes of its precedents and do things right™? But even then, there should be no other files directly in home other than `.murex_profile`.

Nar, the aims are much more modest than that. If I wanted to do thing right then I'd be redesigning TTYs and terminal emulation as well as writing a new shell. In fact to get things like typed pipes working I had to make a number of pragmatic "worse is better" type decisions. _murex_ was more about creating a modern shell based around productivity, readability and safer defaults. XDG is really more of a personal preference than anything.

It's also worth noting that `.murex_modules/` and `.murex_preload` are also profiles. It's a little like how you can have both a `.bashrc` and `.bash_profile` file on some Linux distros.

It's also worth noting that other scripting languages do the same too: Nodes nvm creates a `~/.nvm` directory. Terraform, Perl CPAN and others also writing their modules to `~/.$APPNAME` too. Arguably if _murex_ was to do things right™ it would mean storing the files where they currently are -- not that I'm suggesting that's what I'm planning on doing.

**Comment by lmorg** [comment] 2021-04-27 11:03
I think it's worth pausing for a recap: the options on the table thus far seem to be the following:

1. Respect the XDG environment and fallback to `~` where env vars are not set. Create symlinks in `~` to point to XDG environment.
2. Default to `~` but have an override environmental variable
3. Default to `~` but have it overridden via compile time flag

As much as I like the symlink idea solving peoples expectations, I just see far too many issues with XDG (it's not always set, it's not really cross platform, it's not simple to reason and even when it all works as to be expected 99% of the time, there's a dozen edge cases that apply specifically to shells where it could still go wrong).

I wasn't originally in favour of a _murex_ specific env var but actually I'm coming around to that. Temp directories are already stored in an env var and it wouldn't add any complexity to add a new one. Plus there is already `murex-package: reload` available if one did need to reload modules (eg if you started _murex_ then realised the env var wasn't set).

Compiled in paths solve a lot of the immediate issues, but long term wise it's not great for anyone who isn't compiling their own copy of _murex_.

## Proposal: `$HOME` default, _murex_ specific env var override

If I did add env vars it might look like the following:

```
MUREX_PRELOAD="~/.murex_preload"
MUREX_MODULES="~/.murex_modules/"
MUREX_PROFILE="~/.murex_profile"
```

(I might as well make all 3 paths configurable)

Then if you only wanted _murex_ file in your home directory you could configure it to look like this:

```
# ~/.murex_preload

MUREX_MODULES=~/.config/murex/
MUREX_PROFILE=~/.config/murex/profile.mx
```

`~/.murex_preload` is always loaded first and that would consistently set your _murex_ environment. Then any preferences you want to change you'd have to `vi $MUREX_PROFILE` and add it there. (or you could write all three envs in your `profile.d` if you'd prefer).

I should add the above isn't a decision -- just a proposal.

**Comment by piegamesde** [comment] 2021-04-27 16:29
> In fact, where are $XDG_CONFIG_HOME and $XDG_DATA_HOME set? It doesn't appear to be set on my ArchLinux systems nor any of my CentOS and Ubuntu Server systems either.

Only few systems set it explicitly, because not setting it implies the default values, which are sane. The *how*, well it's a tricky question, which will lead you down the rabbit hole of shell and environment initialization. Effectively, you have multiple actors:

- The shell, which will start sourcing `/etc/bashrc` or something, which will source `~/.bashrc` and also `/etc/profile`.
- The desktop environment, which has its own scripts to bootstrap
- The systemd session, which nowadays can also manage your environment variables.

Personally, I set the variables in a script in `/etc/profiles.d/`, because all my Shells as well as Gnome source it.

> Cache gets written to the temp directory

Ah, okay. Temp files are a separate issue, $XDG_CACHE_HOME is about *persistent* caching.

**Comment by lmorg** [comment] 2021-04-27 18:36
> The _how_, well it's a tricky question

Yeah, that's what bothers me. I'm all for moving dot files out of `$HOME` but XDG, as a specification, just creates more problems than it solves.

> Ah, okay. Temp files are a separate issue, $XDG_CACHE_HOME is about _persistent_ caching.

Cache files are just temporary files -- the difference is really how long those files need to remain persistent. Given a reboot kills your shell session, it makes more sense to write the shell's cache to a non-persistent volume. Anything that needs to remain persistent across sessions is no longer cache, it's config. And thus you'd describe that in code.

What's your thoughts on the proposal above?

**Comment by lmorg** [comment] 2021-04-27 19:15
> Ah, okay. Temp files are a separate issue, $XDG_CACHE_HOME is about persistent caching.

Yeah I get that but since cache files are themselves just temporary files and a shell's cache only needs to live as long as the shell session, there's little point storing the cache on a persistent volume. Any cache that does need to be persistent across sessions is no longer a cache, it's config. So you'd define that in code in your profile.

**Comment by piegamesde** [comment] 2021-04-27 19:34
1. I'm a bit skeptical towards the "fallback to ~ where env vars are not set". Also I don't fully understand why since this means that there would be no symlinks? Maybe I just misunderstand you.
2. Sounds sane
3. Please not. "Managed a custom compile settings for a package" is a great barrier compared to "set some environment variable.

**Comment by lmorg** [comment] 2021-05-06 10:38
> I'm a bit skeptical towards the "fallback to ~ where env vars are not set". Also I don't fully understand why since this means that there would be no symlinks? Maybe I just misunderstand you.

Nope, that's my error. Sorry. You're right regarding the symlinks.

---

It's been nearly 10 days since the last exchange and no other comments providing feedback. My personal preference is option 2 and I've not seen any complaints against that so I'll add that request to the backlog of work

**Comment by lmorg** [comment] 2021-05-24 00:03
@piegamesde 

Version `2.1.5000` includes support for custom profile paths based on the `MUREX_PROFILE` et al env vars. Docs updated: https://murex.rocks/docs/user-guide/profile.html

I'll leave this issue open for a little while in case this update introduces any regression bugs. But I've written a crap load of additional unit tests so I'm hopeful

**Comment by lmorg** [comment] 2021-06-01 22:59
I'm going to close this issue on the assumption that everyone is happy. I can always re-open it again if needed.

**Closed by lmorg** 2021-06-01 22:59 UTC
Labels: enhancement, in progress

**Comment by JustMarkov** [comment] 2024-12-23 05:01
> I'm going to close this issue on the assumption that everyone is happy. I can always re-open it again if needed.

@lmorg,
According to https://orefalo.github.io/murex-docs/user-guide/profile.html it is possible to configure preload, modules and profile paths, but .murex_history path is not configurable?
I tried setting something like `MUREX_HISTORY`, but it looks like something like that is not implemented.
