### ISSUE TITLE
panic in murex readline

### ISSUE THREAD

**Issue by kquick** [lmorg/murex#617] opened 2023-06-14 20:54 UTC
**Describe the bug:**
I had a line in-progress and wanted to jump to the start of the line after typing a relatively long command (approx 83+ chars).  I am new  to murex, so I was trying combinations of ESC, 0, Ctrl-b, ESC in sort of a haphazard fashion when all of a sudden I got the following:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/lmorg/murex/utils/readline.(*Instance).readlineInput(0xc0000e0700, {0xc002c80000?, 0xc0000380f0?, 0x1?})
        github.com/lmorg/murex/utils/readline/readline.go:476 +0xf9
github.com/lmorg/murex/utils/readline.(*Instance).Readline(0xc0000e0700)
        github.com/lmorg/murex/utils/readline/readline.go:274 +0x1887
github.com/lmorg/murex/shell.ShowPrompt()
        github.com/lmorg/murex/shell/shell.go:153 +0x345
github.com/lmorg/murex/shell.Start()
        github.com/lmorg/murex/shell/shell.go:86 +0x2aa
main.startMurex()
        github.com/lmorg/murex/main.go:153 +0x6a
main.main()
        github.com/lmorg/murex/main.go:40 +0x5d
$
```

**Platform (please complete the following information):**
Linux, st terminal emulator
 - OS, output from `uname -a` if supported: 
     Linux
 - Terminal Emulator: [e.g. iTerm2, Konsole]
      st
 - Murex version, output from `version --no-app-name`: [e.g. 2.12.1200]
      v4.1.6140

**Comment by lmorg** [comment] 2023-06-14 22:29
Ouch. That should never happen. I've written a patch that will allow that function to exit safely. Identifying the root cause of that will take me a little longer :)

Will push the patch tomorrow

**Comment by lmorg** [comment] 2023-06-20 08:35
Merged to `master`

**Closed by lmorg** 2023-06-20 08:35 UTC
Labels: bug, in progress, deployed to `develop`
